<?php

/**
 * @file
 * Contains commerce_securepayau.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_securepayau_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_securepayau module.
    case 'help.page.commerce_securepayau':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SecurePay') . '</p>';
      return $output;

    default:
  }
}
